### ISSUE TITLE
Fail build if publishing fails

### ISSUE THREAD

**Issue by YaManicKill** [maxleiko/grunt-publish#3]
Is it possible to get the grunt build to error if publishing fails. Currently, it just logs that it fails, and moves on, but if publishing doesn't work on my CI server, I want to be aware of that before I npm install something else.

Thanks

**Comment by maxleiko** [comment]
@YaManicKill I did not touch that module since 2 years. I'm pretty sure that something else has been made and is better than this.  
I would advise you to try to find an alternative to this package that does the same thing :)

**Comment by YaManicKill** [comment]
Hey, thanks, there isn't anything I have found that does the same thing and is any more up to date. Thanks anyway.

**Comment by maxleiko** [comment]
Okay, I'll have a look at it then ASAP.

**Comment by YaManicKill** [comment]
Oh no, now I feel bad about you taking time to do this. It's not an absolute necessity. We can probably live without it. It's just another argument to the team that we should be moving away from grunt as we don't do anything with grunt that can't be done just with npm scripts, and then we don't have to rely on these third party plugins.

**Comment by maxleiko** [comment]
@YaManicKill try `v1.0.0` out :+1:

**Comment by AlMcKinlay** [comment]
Thanks so much, that's brilliant. You are what's great about the world.

**Comment by maxleiko** [comment]
You have to use the `exitOnFailure` option in your Gruntfile.js in order for the plugin to process the tasks in series instead of parallel.

**Comment by AlMcKinlay** [comment]
Yeah, I saw that in your commit. My colleague is just testing it out right now.
